# Example for dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../base

namespace: feature-1

commonLabels:
  stage: feature-1

patches:
- target:
    kind: Deployment
    name: my-app
  path: deployment.yml

- target:
    kind: Service
    name: myapp-service
  # path: service.yml
  patch: |-
      - op: replace
        path: /spec/ports/0/port
        value: 7000
