apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-dev
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  source:
    repoURL: https://github.com/vikaskumarsardar/test-argo.git
    targetRevision: main
    path: overlays/dev
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true  
    automated:
      selfHeal: true
      prune: true
