# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: dev-app
# spec:
#   destination:
#     server: 'https://kubernetes.default.svc'
#     namespace: dev
#   source:
#     repoURL: https://github.com/vikaskumarsardar/test-argo.git
#     targetRevision: main
#     path: overlays/dev
#   project: default
#   syncPolicy:
#     syncOptions:
#     - CreateNamespace=true  
#     automated:
#       selfHeal: true
#       prune: true

# ---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-dev
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: staging
  source:
    repoURL: https://github.com/vikaskumarsardar/test-argo.git
    targetRevision: main
    path: overlay/staging
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true  
    automated:
      selfHeal: true
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-dev
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  source:
    repoURL: https://github.com/vikaskumarsardar/test-argo.git
    targetRevision: main
    path: overlay/prod
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true  
    automated:
      selfHeal: true
      prune: true