# Example for dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: prod

commonLabels:
  stage: prod

patches:
- target:
    kind: Deployment
    name: my-app
  path: deployment.yml

# - target:
#     kind: Service
#     name: dev-balancer
#   patch: service.yml

