apiVersion: v1
kind: Service
metadata:
  name: prod-balancer
spec:
  selector:
    app: prod-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 3456 # Use the port specified in your Node.js application
  type: LoadBalancer
