apiVersion: v1
kind: Service
metadata:
  name: dev-balancer
spec:
  selector:
    app: dev-app
  ports:
    - protocol: TCP
      port: 6789
      targetPort: 3456 # Use the port specified in your Node.js application
  type: LoadBalancer
