apiVersion: v1
kind: Service
metadata:
  name: first-balancer-service
spec:
  selector:
    app: first-service
  ports:
    - protocol: TCP
      port: 6789
      targetPort: 3456 # Use the port specified in your Node.js application
  type: LoadBalancer
