# Example for dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- service.yml

commonLabels:
  app: my-kustomize-app
namePrefix:
  kustom-
# nameSuffix:
#   -v1    