# Example for dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: Deployment
    name: dev-deployment
  patch: deployment.yml

- target:
    kind: Service
    name: dev-balancer
  patch: service.yml
