# Example for dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: stage

commonLabels:
  stage: stage
  app: my-customize-app-stage
nameSuffix:
  -stage

patches:
- target:
    kind: Deployment
    name: my-app
  path: deployment.yml

- target:
    kind: Service
    name: myapp-service
  # path: service.yml
  patch: |-
      - op: replace
        path: /spec/ports/0/port
        value: 8000
