apiVersion: v1
kind: Service
metadata:
  name: stage-balancer
spec:
  selector:
    app: stage-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 3456 # Use the port specified in your Node.js application
  type: LoadBalancer
